# Generated by Django 3.1.6 on 2021-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210219_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='original_shopping_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
