# Generated by Django 3.1.6 on 2021-02-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0003_auto_20210223_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='profiles.userprofile'),
        ),
    ]
