# Generated by Django 3.1.6 on 2021-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210218_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
