# Generated by Django 3.1.6 on 2021-02-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210218_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
