# Generated by Django 3.1.6 on 2021-02-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210218_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
